// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOEHCwNXSrGXhYuzv3rp2JsPxjOc0a-Q',
    appId: '1:431117855655:web:15de3d78e6662e5c4ca482',
    messagingSenderId: '431117855655',
    projectId: 'noeixo-textil',
    authDomain: 'noeixo-textil.firebaseapp.com',
    storageBucket: 'noeixo-textil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwknjg_RwcycB2ZIV3ipY_1gBYY3Wqvxk',
    appId: '1:431117855655:android:4ea71bee842bdd654ca482',
    messagingSenderId: '431117855655',
    projectId: 'noeixo-textil',
    storageBucket: 'noeixo-textil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQT5o6KmPZ0EWJGGIpferCikQuzajEFYY',
    appId: '1:431117855655:ios:69957f159c8598b74ca482',
    messagingSenderId: '431117855655',
    projectId: 'noeixo-textil',
    storageBucket: 'noeixo-textil.firebasestorage.app',
    iosBundleId: 'com.example.noeixoTextilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQT5o6KmPZ0EWJGGIpferCikQuzajEFYY',
    appId: '1:431117855655:ios:69957f159c8598b74ca482',
    messagingSenderId: '431117855655',
    projectId: 'noeixo-textil',
    storageBucket: 'noeixo-textil.firebasestorage.app',
    iosBundleId: 'com.example.noeixoTextilApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXOEHCwNXSrGXhYuzv3rp2JsPxjOc0a-Q',
    appId: '1:431117855655:web:11f7e8bf00abc7df4ca482',
    messagingSenderId: '431117855655',
    projectId: 'noeixo-textil',
    authDomain: 'noeixo-textil.firebaseapp.com',
    storageBucket: 'noeixo-textil.firebasestorage.app',
  );
}
